name: Minuscode
exclude: Guardfile
permalink: none
markdown: kramdown

sass:
  sass_dir: public/css/src
  style: compressed
includes:
  google_tracking_id: 'UA-33665278-1'
exclude:
  ['assets', 'config.rb', 'Guardfile', 'Procfile', 'Procfile.example', 'Gemfile', 'Gemfile.lock']
gems:
  - jekyll-sitemap
collections:
  - persons
  - works
