name: Minuscode
auto: true
exclude: Guardfile
permalink: none
#baseurl: /minuscode.github.io

includes:
  google_tracking_id: 'UA-33665278-1'
exclude:
  ['assets', 'config.rb', 'Guardfile', 'Procfile', 'Procfile.example', 'Gemfile', 'Gemfile.lock']
